### ISSUE TITLE
Error when running docker build

### ISSUE THREAD

**Issue by amarmashruwala** [Envek/dockerized-browser-streamer#2]
sudo docker build . -t webrtc-streamer
[+] Building 0.0s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                          0.0s
 => => transferring dockerfile: 2B                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                               0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount185229680/Dockerfile: no such file or directory
Any idea what this error means? 
thank you

**Comment by Envek** [comment]
Why do you use `sudo`? It may affect build somehow (usually it is not recommended to run docker build with superuser privileges).

Try to configure your system to allow running Docker without sudo.

---

But in general: no, no idea why it fails with such an error. I checked it right now and it builds on my Linux machine.

**Comment by amarmashruwala** [comment]
thanks i have fixed this issue.

**Comment by Envek** [comment]
What was the problem? Just curious

**Comment by amarmashruwala** [comment]
Sorry i had mistakenly cloned the incorrect Github project.
